export const LOAD_GROUPS = "LOAD_GROUPS";
export const POPULATE_GROUPS = "POPULATE_GROUPS";
export const LOAD_GROUPS_WORKING = "LOAD_GROUPS_WORKING";
export const CLEAR_GROUPS = "CLEAR_GROUPS";
export const DELETE_GROUP = "DELETE_GROUP";
export const LOAD_QVW_FIELDS = "LOAD_QVW_FIELDS";
export const CLEAR_QVW_FIELDS = "CLEAR_QVW_FIELDS";
