export const LOAD_VARIABLES = "LOAD_VARIABLES";
export const LOAD_VARIABLES_WORKING = "LOAD_VARIABLES_WORKING";
export const VAR_SET_SEARCH_TERM = "VAR_SET_SEARCH_TERM";
export const VAR_SET_GROUP_FILTER = "VAR_SET_GROUP_FILTER";
export const CLEAR_VARIABLES = "CLEAR_VARIABLES";
export const VAR_UPDATE = "VAR_UPDATE";
